### ISSUE TITLE
Players have too much mass, they can push away tanks

### ISSUE THREAD

**Issue by williamchong007** [vicksonzero/tank-beyond-repair#34]
as title, which means you can push your tanks to win, or push enemy tanks away to prevent losing.

Expect: player cannot affect tank movement

**Comment by vicksonzero** [comment]
i like being able to push in the lateral direction, but yes... how to prevent pushing forward towards the goal??

**Comment by 199911** [comment]
how about increase bullet speed, lower attack speed?

So player may die when pushing tank forward
