### ISSUE TITLE
There should be visual change on tank and item upgrade

### ISSUE THREAD

**Issue by williamchong007** [vicksonzero/tank-beyond-repair#38]
Currently you cannot observe tank and item upgrade without going close to them. Maybe add some tint or color or sprite change according to upgrades?

Suggestion: for damage upgraded tanks, increase size of barrrel, or tint to red, or add red decorations on tank.

**Comment by vicksonzero** [comment]
added for the following:

- range
- damage
- maxHP

dunno how to represent these:
- movementSpeed
- attackSpeed

maybe attackSpeed can be represented by recoil?

**Comment by vicksonzero** [comment]
resolved for now. will open new issues for new directions
